# Generated by Django 2.1.1 on 2018-09-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_scont'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scont',
        ),
    ]
