# Generated by Django 2.1.1 on 2018-09-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_delete_scont'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('adress1', models.CharField(max_length=50, verbose_name='название')),
                ('contact1', models.TextField(max_length=200, verbose_name='tel')),
                ('maile1', models.CharField(max_length=50, verbose_name='почта')),
            ],
        ),
    ]
