# Generated by Django 2.1.1 on 2018-09-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_scont'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scont',
            name='adress1',
            field=models.CharField(max_length=50, verbose_name='adress'),
        ),
    ]
