# Generated by Django 2.1.1 on 2018-09-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20180921_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPrimary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('texts', models.TextField(verbose_name='текст')),
                ('doptext1', models.TextField(blank=True, max_length=100, verbose_name='доп. текст 1')),
                ('doptext2', models.TextField(blank=True, max_length=100, verbose_name='доп. текст 2')),
                ('doptext3', models.TextField(blank=True, max_length=100, verbose_name='доп. текст 3')),
                ('doptext4', models.TextField(blank=True, max_length=100, verbose_name='доп. текст 4')),
            ],
        ),
    ]
