# Generated by Django 2.1.1 on 2018-09-29 00:13

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to=ticket.models.generate_filename),
        ),
    ]
