# Generated by Django 2.1.1 on 2018-09-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_priceuslugi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceuslugi',
            name='summ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
