# Generated by Django 2.1.1 on 2018-09-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20180929_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceuslugi',
            name='summ',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='сумма'),
        ),
    ]
