# Generated by Django 2.1.1 on 2018-10-01 13:30

from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_auto_20180930_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatSchetchic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'кат Счетчик',
                'verbose_name_plural': 'кат Счетчики',
            },
        ),
        migrations.CreateModel(
            name='Schetchic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('text', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, upload_to=ticket.models.generate_filename1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.CatSchetchic', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Счетчик',
                'verbose_name_plural': 'Счетчики',
            },
        ),
        migrations.CreateModel(
            name='VodTepSchetchic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.CatSchetchic', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'под Счетчик',
                'verbose_name_plural': 'под Счетчики',
            },
        ),
        migrations.AddField(
            model_name='schetchic',
            name='vodcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.VodTepSchetchic', verbose_name='Счетчик'),
        ),
    ]
