# Generated by Django 2.1.1 on 2018-10-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_auto_20181001_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Du',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.CatSchetchic', verbose_name='Категория')),
                ('vodcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.VodTepSchetchic', verbose_name='Счетчик')),
            ],
            options={
                'verbose_name': 'Ду',
                'verbose_name_plural': 'Ду',
            },
        ),
        migrations.AlterField(
            model_name='schetchic',
            name='vodcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.VodTepSchetchic', verbose_name='вод теп Счетчик'),
        ),
        migrations.AddField(
            model_name='schetchic',
            name='shdu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Du', verbose_name='ду'),
        ),
    ]
