# Generated by Django 2.1.1 on 2018-10-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_auto_20181001_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinir',
            name='category',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.RemoveField(
            model_name='taxomkrylchat',
            name='category',
        ),
        migrations.RemoveField(
            model_name='taxomturb',
            name='category',
        ),
        migrations.DeleteModel(
            name='Teploschetchiki',
        ),
        migrations.DeleteModel(
            name='Combinir',
        ),
        migrations.DeleteModel(
            name='TaxomKrylchat',
        ),
        migrations.DeleteModel(
            name='TaxomTurb',
        ),
        migrations.DeleteModel(
            name='Vodoschetchiki',
        ),
    ]
