# Generated by Django 2.1.1 on 2018-10-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_auto_20181002_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schetchic',
            name='shdu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Du', verbose_name='ду'),
        ),
    ]
