# Generated by Django 2.1.1 on 2018-10-02 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_auto_20181002_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schetchic',
            name='shdu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Du', verbose_name='ду'),
        ),
    ]
