# Generated by Django 2.1.1 on 2018-10-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0020_auto_20181002_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='du',
            name='vodcategory',
        ),
        migrations.AddField(
            model_name='du',
            name='vodcategory',
            field=models.ManyToManyField(to='ticket.VodTepSchetchic', verbose_name='Счетчик'),
        ),
    ]
