# Generated by Django 2.1.1 on 2018-10-03 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_auto_20181003_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schetchic',
            name='shdu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Du', verbose_name='ду'),
        ),
    ]
