# Generated by Django 2.1.1 on 2018-10-03 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0025_auto_20181003_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schetchic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='schetchic',
            name='shdu',
        ),
        migrations.RemoveField(
            model_name='schetchic',
            name='vodcategory',
        ),
        migrations.AlterModelOptions(
            name='vodtepschetchic',
            options={'ordering': ['category'], 'verbose_name': 'под Счетчик', 'verbose_name_plural': 'под Счетчики'},
        ),
        migrations.DeleteModel(
            name='Schetchic',
        ),
    ]
