# Generated by Django 2.1.1 on 2018-10-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0027_schetchic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schetchic',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
