# Generated by Django 2.1.1 on 2018-10-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0028_auto_20181003_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='vodtepschetchic',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
