# Generated by Django 2.1.1 on 2018-10-03 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0029_vodtepschetchic_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vodtepschetchic',
            name='text',
        ),
    ]
