# Generated by Django 2.1.1 on 2018-10-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0031_auto_20181003_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('telephon', models.PositiveIntegerField(verbose_name='Телефон')),
                ('email_t', models.EmailField(blank=True, max_length=254, verbose_name='Ваш @email')),
                ('comment', models.TextField(verbose_name='Коментарии')),
                ('datetime_t', models.DateTimeField(auto_now_add=True, verbose_name='Дата, время')),
            ],
        ),
    ]
