# Generated by Django 2.1.2 on 2018-10-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0033_auto_20181022_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schetchic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='schetchic',
            name='shdu',
        ),
        migrations.RemoveField(
            model_name='schetchic',
            name='vodcategory',
        ),
        migrations.DeleteModel(
            name='Schetchic',
        ),
    ]
