# Generated by Django 2.1.2 on 2018-10-22 18:54

from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0034_auto_20181022_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schetchic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('text', models.TextField(blank=True, verbose_name='описание')),
                ('specifications', models.TextField(blank=True, verbose_name='характиристики')),
                ('image', models.ImageField(blank=True, upload_to=ticket.models.generate_filename1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.CatSchetchic', verbose_name='Категория')),
                ('shdu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.Du', verbose_name='ду')),
                ('vodcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.VodTepSchetchic', verbose_name='вод теп Счетчик')),
            ],
            options={
                'verbose_name': 'Счетчик',
                'verbose_name_plural': 'Счетчики',
                'ordering': ['title'],
            },
        ),
    ]
